[package]
name = "rust-bot"
version = "0.1.0"
authors = ["diluent"]

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
# rocket_codegen = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
